AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy EC2 instances and ALB

Parameters:
  VPC:
    Type: String
    Description: VPC ID
  PublicSubnet1:
    Type: String
    Description: Public Subnet 1 ID
  PublicSubnet2:
    Type: String
    Description: Public Subnet 2 ID
  PrivateSubnet1:
    Type: String
    Description: Private Subnet 2 ID
  PrivateSubnet2:
    Type: String
    Description: Private Subnet 2 ID
  WebInstanceSecurityGroup:
    Type: String
    Description: Web Instance SG ID
  BastionSecurityGroup:
    Type: String
    Description: Bastion SG ID
  ALBSecurityGroup:
    Type: String
    Description: ALB SG ID
Resources:
  WebServerInstance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: "ami-09bd942ffa33583ff"
      KeyName: 'vockey'
      SecurityGroupIds:
        - Ref: WebInstanceSecurityGroup
      SubnetId:
        Ref: PrivateSubnet1
      Tags:
        - Key: Name
          Value: WebServerInstance1
  WebServerInstance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: "ami-09bd942ffa33583ff"
      KeyName: 'vockey'
      SecurityGroupIds:
        - Ref: WebInstanceSecurityGroup
      SubnetId:
        Ref: PrivateSubnet2
      Tags:
        - Key: Name
          Value: WebServerInstance2
  BastionHostInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: "ami-0230bd60aa48260c6"
      KeyName: 'vockey'
      SecurityGroupIds:
        - Ref: BastionSecurityGroup
      SubnetId:
        Ref: PublicSubnet2
      Tags:
        - Key: Name
          Value: BastionHostInstance
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: ALBTargetGroup
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: ALBTargetGroup
      LoadBalancerArn:
        Ref: ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: ALBTargetGroup
      Port: 80
      Protocol: HTTP
      TargetType: instance
      Targets:
        - Id: !Ref WebServerInstance1
        - Id: !Ref WebServerInstance2
      VpcId:
        Ref: VPC
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: ApplicationLoadBalancer
      Subnets:
        - Ref: PublicSubnet1
        - Ref: PublicSubnet2
      SecurityGroups:
        - Ref: ALBSecurityGroup
Outputs:
  ApplicationLoadBalancer:
    Description: Application Load Balancer URL/DNS.
    Value:
      Fn::GetAtt:
        - ApplicationLoadBalancer
        - DNSName
  BastionHostInstance:
    Description: Bastion Host Public IP
    Value:
      Fn::GetAtt:
        - BastionHostInstance
        - PublicIp